### ISSUE TITLE
[BcMathNumber::performOperation] Specified scale 0 conflict

### ISSUE THREAD

**Issue by fyrye** [dbojdo/bcmath#4]
The determination of scale in `BcMathNumber::performOperation` returns unexpected results.
```php
$scale = (int) ($scale ?: self::$defaultScale);
````
Will return as `self::defaultScale` when a scale of `0` is specified.
e.g.

```php
echo BcMathNumber::create('123.45')
   ->add('1', 0)
   ->getValue(); 
   //returns 124.45000000 - expected 124
```
vs https://3v4l.org/ib3ZC
```php
echo bcadd('123.45', '1', 0); //124
```

The line should be changed to read:
```php
$scale = (int) (null === $scale ? self::$defaultScale : $scale);
````

**Comment by dbojdo** [comment]
@fyrye Thanks for pointing it out. I've put some tests in place to cover this case and I've fixed some more issues I've found during this.
