### ISSUE TITLE
replace self with static so class can be extended

### ISSUE THREAD

**Issue by antman3351** [dbojdo/bcmath#6]
Hello,

I've extended the BcMathNumber class to add an extra (helper) function, just as soon as i call any of the parent methods the return is an instance of the parent class `return new self($num);` instead of the child class `return new static($num);`.

I think in general all the self calls can be replaced with static, or am I missing something?

Anyway, nice class it certainly makes the code a lot more readable compared to the plain bc functions!

**Comment by dbojdo** [comment]
@antman3351 well, in fact this class is not meant to be extended and should be marked "final". Generally, it is not a good practice to extend third party classes in your code. I'm pretty sure you potentially can use another technique to achieve what you need. If you give me an example of what you're trying to do, I could guide you in a right direction. Thanks.

**Comment by antman3351** [comment]
I wanted to add some functions to group together a set of operations to make my code a bit easier to read.
`$discount = BCNum::_($detail['discount'] )->percentageToComplementDec();`

```
class BCNum extends BcMathNumber
{
    /**
     * @param $number
     * @return BCNum
     */
    static function _( $number )
    {
        return new static( $number );
    }

    /**
     * Convert a percentage to it's complement in decimal
     * 1 - $percentage / 100
     * @return BcMathNumber
     */
    public function percentageToComplementDec()
    {
        return static::_( 1 )->sub(
            $this->div( 100 )
        );
    }

    .... other methods ....
}
```

I could make the function static and keep the class as a "helper class" but then I would loose the ability to chain the methods together.

Thanks!

**Comment by dbojdo** [comment]
Well, if you want to keep "chaining", the best practice would be to define YOUR API for your BCNum class and use BcMathNumber class internally to perform all the operations you need.

```php
class BCNum {
    /** @var BcMathNumber */
    private $value;

    public function __construct($num = 0) {
        if (!($num instanceof BcMathNumber)) {
           $num = BcMathNumber::create($num instanceof self ? $num->toString() : (string)$num);
        }
        $this->value = $num;
    }

    public static function create($num = 0)
    {
        return new self($num);
    }

    public function __toString()
    {
        return (string)$this->value;
    }

    public function add($num) {
       return self::create($this->value->add($num));
    }

    public function sub($num) {
       return self::create($this->value->sub($num));
    }

   // etc
}
```

The most important things are:
1. You defined YOUR OWN API - you are not obliged to expose all the methods could be found in BcMathNumber - only these you need and add your methods. You have a full control over your class now!

2. Your class is not tightly couple to the third party code - you're free to change your class implementation, e.g. to use a different library or even write your own implementation.

3. Encapsulation: implementation is hidden, your class client / user have no idea about the third party

4. Your class will never be changed by changes in the third-party (BcMathNumber may add some new methods, etc).

I understand it might look like a bit of overhead, one could even said "code duplication", but it is not. In fact, that's the correct way of dealing with third-party code - using composition, rather the inheritance.

I'll mark the class "final" in version 2.0 of the lib as I mentioned in the previous comment, it should not be extended.

**Comment by dbojdo** [comment]
I guess, that even in your code, the class itself should avoid the name like "BCNum". It probably it could be like "YourDomainNumber". The fact this it uses bcmath underneath is irrelevant for the usage. E.g. `percentageToComplementDec` is a pretty specific operation, so I guess this is what YOUR application needs, it really does not care if it's calculated using plain bcmath, BcMathNumber of even floats but as a result it expects `YourDomainNumber`, and that's the important bit.

**Comment by antman3351** [comment]
Thanks for the design tips!
